## Challenge 2: Sets

There are a lot to learn about Python Sets and the information presented in the lesson is limited due to its length. To learn Python Sets in depth you are strongly encouraged to review the W3Schools tutorial on [Python Sets Examples and Methods](https://www.w3schools.com/python/python_sets.asp) before you work on this lab. Some difficult questions in this lab have their solutions in the W3Schools tutorial.

#### First, import the Python `random` libary

In [1]:
import random

#### In the cell below, create a list named `sample_list_1` with 80 random values. 

Requirements:

* Each value is an integer falling between 0 and 100.
* Each value in the list is unique.

Print `sample_list_1` to review its values

*Hint: use `random.sample` ([reference](https://docs.python.org/3/library/random.html#random.sample)).*

In [20]:
# Your code here 

sample_list_1 = random.sample(range(100), k = 80) 
print(sample_list_1)

[81, 46, 92, 67, 87, 55, 82, 93, 75, 17, 52, 14, 95, 57, 98, 66, 78, 31, 34, 65, 88, 77, 5, 80, 63, 64, 50, 35, 36, 12, 38, 85, 37, 33, 99, 39, 11, 15, 19, 20, 86, 21, 54, 6, 44, 89, 7, 42, 47, 49, 83, 25, 69, 13, 22, 9, 8, 60, 79, 51, 1, 24, 58, 61, 62, 84, 40, 71, 56, 59, 28, 97, 27, 2, 18, 76, 72, 30, 48, 73]

#### Convert `sample_list_1` to a set called `set1`. Print the length of the set. Is its length still 80?

In [21]:
# Your code here
set1 = set(sample_list_1) 

len(set1)

80

#### Create another list named `sample_list_2` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* The values in the list don't have to be unique.

*Hint: Use a FOR loop.*

In [24]:
# Your code here
sample_list_2 = [] 
for i in range(80): 
  r = random.randint(0,100) 
  sample_list_2.append(r) 

  print(sample_list_2)
for i in sample_list_2: 
  count_sl2 = sample_list_2.count(i) 
  print(count_sl2, i) 
print(len(sample_list_2))

[11]
[11, 93]
[11, 93, 53]
[11, 93, 53, 75]
[11, 93, 53, 75, 27]
[11, 93, 53, 75, 27, 42]
[11, 93, 53, 75, 27, 42, 19]
[11, 93, 53, 75, 27, 42, 19, 88]
[11, 93, 53, 75, 27, 42, 19, 88, 35]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25, 98]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25, 98, 25]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25, 98, 25, 71]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25, 98, 25, 71, 4]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25, 98, 25, 71, 4, 92]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25, 98, 25, 71, 4, 92, 63]
[11, 93, 53, 75, 27, 42, 19, 88, 35, 19, 31, 100, 1, 56, 87, 32, 17, 73, 49, 85, 82, 16, 28, 15, 14, 8, 69, 11, 99, 10, 22, 6, 17, 27, 82, 74, 90, 26, 99, 73, 48, 26, 73, 70, 13, 18, 22, 5, 91, 63, 82, 98, 47, 54, 35, 70, 2, 57, 61, 5, 83, 55, 23, 35, 63, 35, 97, 24, 47, 26, 1, 11, 25, 98, 25, 71, 4, 92, 63, 51]
3 11
1 93
1 53
1 75
2 27
1 42
2 19
1 88
4 35
2 19
1 31
1 100
2 1
1 56
1 87
1 32
2 17
3 73
1 49
1 85
3 82
1 16
1 28
1 15
1 14
1 8
1 69
3 11
2 99
1 10
2 22
1 6
2 17
2 27
3 82
1 74
1 90
3 26
2 99
3 73
1 48
3 26
3 73
2 70
1 13
1 18
2 22
2 5
1 91
3 63
3 82
2 98
2 47
1 54
4 35
2 70
1 2
1 57
1 61
2 5
1 83
1 55
1 23
4 35
3 63
4 35
1 97
1 24
2 47
3 26
2 1
3 11
2 25
2 98
2 25
1 71
1 4
1 92
3 63
1 51
80

#### Convert `sample_list_2` to a set called `set2`. Print the length of the set. Is its length still 80?

In [27]:
# Your code here
set2 = set(sample_list_2) 
print(len(set2))
print(len(sample_list_2))

56
80

#### Identify the elements present in `set1` but not in `set2`. Assign the elements to a new set named `set3`.

In [30]:
# Your code here
set3 = set1.difference(set2) 
set3

{7,
 9,
 12,
 20,
 21,
 30,
 33,
 34,
 36,
 37,
 38,
 39,
 40,
 44,
 46,
 50,
 52,
 58,
 59,
 60,
 62,
 64,
 65,
 66,
 67,
 72,
 76,
 77,
 78,
 79,
 80,
 81,
 84,
 86,
 89,
 95}

#### Identify the elements present in `set2` but not in `set1`. Assign the elements to a new set named `set4`.

In [33]:
# Your code here
set4 = set2.difference(set1)
set4

{4, 10, 16, 23, 26, 32, 53, 70, 74, 90, 91, 100}

#### Now Identify the elements shared between `set1` and `set2`. Assign the elements to a new set named `set5`.

In [34]:
# Your code here
set5 = set1.intersection(set2) 
set5

{1,
 2,
 5,
 6,
 8,
 11,
 13,
 14,
 15,
 17,
 18,
 19,
 22,
 24,
 25,
 27,
 28,
 31,
 35,
 42,
 47,
 48,
 49,
 51,
 54,
 55,
 56,
 57,
 61,
 63,
 69,
 71,
 73,
 75,
 82,
 83,
 85,
 87,
 88,
 92,
 93,
 97,
 98,
 99}

#### What is the relationship among the following values:

* len(set1)
* len(set2)
* len(set3)
* len(set4)
* len(set5)

Use a math formular to represent that relationship. Test your formular with Python code.

In [35]:
# Your code here
len(set1)
len(set2)
len(set3)
len(set4)
len(set5)


print(set1.issubset(set2))
print(set1.issubset(set3))
print(set1.issubset(set4))
print(set1.issubset(set5))

len(set1) + len(set2) == len(set4) - len(set5)

len(set3) == len(set1) + len(set4)

False
False
False
False

False

#### Create an empty set called `set6`.

In [36]:
# Your code here
set6 = set()

#### Add `set3` and `set5` to `set6` using the Python Set `update` method.

In [37]:
# Your code here
set6.update(set3, set5) 
print(set6)

{1, 2, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 24, 25, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 44, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 71, 72, 73, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 92, 93, 95, 97, 98, 99}

#### Check if `set1` and `set6` are equal.

In [38]:
# Your code here
set1 == set6

True

#### Check if `set1` contains `set2` using the Python Set `issubset` method. Then check if `set1` contains `set3`.*

In [39]:
# Your code here
set1.issubset(set2)  
set1.issubset(set3)

False

#### Using the Python Set `union` method, aggregate `set3`, `set4`, and `set5`. Then aggregate `set1` and `set2`. 

#### Check if the aggregated values are equal.

In [40]:
# Your code here
sets = set3.union(set4, set5, set2, set1) 
print(sets)

{1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 95, 97, 98, 99, 100}

#### Using the `pop` method, remove the first element from `set1`.

In [42]:
# Your code here
remove = set1.pop()
print(remove)
print(set1)

1
{2, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 24, 25, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 44, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 71, 72, 73, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 92, 93, 95, 97, 98, 99}

#### Remove every element in the following list from `set1` if they are present in the set. Print the remaining elements.

```
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
```

In [43]:
# Your code here
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]

new_list=set1
for value in list_to_remove:
    if value in set1:
     new_list = set1.remove(value)
print(new_list)

None